ROOT_DIR := $(realpath ../..)
include $(ROOT_DIR)/config.mk

all:
	$(MAKE) -C omp_hello

run-simx:
	$(MAKE) -C omp_hello run-simx

run-rtlsim:
	$(MAKE) -C omp_hello run-rtlsim

clean:
	$(MAKE) -C omp_hello clean